import type { NextPage } from 'next'
import Head from 'next/head'
import AppBarM from '../components/appBar';
import HomeHeader from '../components/homeHeader';
import ProjectData from '../components/projectData';
import Toolbar from '@mui/material/Toolbar';
import Button from '@mui/material/Button';
import TablePert from '../components/table';

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>PERT</title>
        <meta name="description" content="Generated by Violeta" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <AppBarM title='VM'/>
        <HomeHeader></HomeHeader>
        <ProjectData/>
        <Toolbar>
          <h5 className='subtitle'>ACTIVITIES</h5>
          <Button className='button3'>
            +
          </Button>
        </Toolbar>
        
      </main>
    </div>
  )
}

export default Home
